### ISSUE TITLE
Allow Delete Users from Okta IDP

### ISSUE THREAD

**Issue by estein9825** [paralus/dashboard#157] opened 2023-01-31 21:56 UTC
Currently, local users are allowed to be deleted. However, if you setup Okta, you can't. The users are just _there_. In the case where the okta configuration changes, but the email is the same, it can cause an error since the internal configurations are different. We should be able to delete the same user.

**Comment by techmaharaj** [comment] 2023-02-02 07:15
Moving this to the dashboard repo as this is a UI functionality that needs to be added.

**Comment by niravparikh05** [comment] 2023-02-17 04:58
seems like a duplicate of https://github.com/paralus/paralus/issues/143, tracking it there.

**Comment by niravparikh05** [comment] 2023-02-28 10:58
@estein9825 this is fixed with paralus v0.2.2 release. Kindly verify, closing this issue for now.

**Closed by niravparikh05** 2023-02-28 10:58 UTC
Labels: duplicate, enhancement
